name: dependencies
description: "Dependencies module created by flutter_modular"

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_modular: ^5.0.3
  dio: ^5.3.2
  internet_connection_checker: ^1.0.0+1
  flutter_svg: ^2.0.0+1
  flutter_bloc: ^8.1.2
  equatable: ^2.0.5
  mockito: ^5.3.2
  dartz: ^0.10.1
  get_storage: ^2.0.2



dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
